### ISSUE TITLE
Update the Changelog

### ISSUE THREAD

**Issue by guzzur** [strigo/vscode-linear-extension#11]
We have now 0.0.3 released but the Changelog doesn't have any description on what is there yet.

**Comment by nir0s** [comment]
I think that the changelog.md file reflect the current feature set, it doesn't just reflect that we've released 0.0.3.

**Comment by guzzur** [comment]
> I think that the changelog.md file reflects the current feature set, it doesn't just reflect that we've released 0.0.3.

Absolutely, but now it doesn't describe what was released and in which version, and what wasn't.
